// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2PRvSgyBELVmDP7IuNVrLOhcbA51gdGo',
    appId: '1:162679290912:web:545655cd8567a9bd86d045',
    messagingSenderId: '162679290912',
    projectId: 'haven-10406',
    authDomain: 'haven-10406.firebaseapp.com',
    storageBucket: 'haven-10406.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9YY5Ti9ckkSiTuQNtN32IuvpSR9b5kDI',
    appId: '1:162679290912:android:739e50b99fd038c286d045',
    messagingSenderId: '162679290912',
    projectId: 'haven-10406',
    storageBucket: 'haven-10406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMrcwteMBn8ppyqJvc_yZty2rTkJv_DP8',
    appId: '1:162679290912:ios:7402c6530bbc0ac386d045',
    messagingSenderId: '162679290912',
    projectId: 'haven-10406',
    storageBucket: 'haven-10406.firebasestorage.app',
    iosBundleId: 'ng.com.sirteefyapps.haven.haven',
  );
}
